Config:
  AuditSchemaName: audit
  TableFieldIndentation: 4
  TypeMap:
  - Type: ss
    Output: NVARCHAR(50)
  - Type: ls
    Output: NVARCHAR(500)
  - Type: d
    Output: DECIMAL(19, 6)
  - Type: i
    Output: INT
  - Type: pk
    Output: INT IDENTITY(1, 1) PRIMARY KEY
  - Type: dt
    Output: DATETIMEOFFSET
  - Type: bi
    Output: BIGINT
  - Type: guid
    Output:   UNIQUEIDENTIFIER
  - Type: upc
    Output: CHAR(12)
  - Type: ean
    Output: CHAR(13)
  - Type: gtin
    Output: CHAR(14)
  - Type: asin
    Output: CHAR(10)
  - Type: b
    Output: BIT
  AuditFields:
  - Name: Id
    Type: pk
  - Name: EffDateTime
    Type: dt
  - Name: ExpDateTime
    Type: dt
  - Name: Ver
    Type: bi
Tables:
  - Name: Tenant
    Fields:
    - Name: TenantGuid
      Type: guid
    - Name: Desc
      Type: ls
    Unique:
    - TenantGuid
  - Name: ActionType
    Fields:
    - Name: TenantId
      Type: i
    - Name: ExtId
      Type: ss
    - Name: Desc
      Type: ls
    Unique:
    - TenantId
    - ExtId
  - Name: Action
    Fields:
    - Name: TenantId
      Type: i
    - Name: ActionTypeId
      Type: i
    - Name: UserId
      Type: i
    - Name: PerformedDateTime
      Type: dt
    Unique:
    - n
  - Name: User
    Fields:
    - Name: TenantId
      Type: i
    - Name: ExtId
      Type: ss
    - Name: Desc
      Type: ls
    Unique:
    - TenantId
    - ExtId
  - Name: AltIdType
    Fields:
    - Name: TenantId
      Type: i
    - Name: ExtId
      Type: ss
    - Name: Desc
      Type: ls
    Unique:
    - ExtId
  - Name: AltId
    Fields:
    - Name: TenantId
      Type: i
    - Name: AltIdType
      Type: i
    - Name: Value
      Type: ss
    Unique:
    - TenantId
    - AltIdTypeId
    - Value
  - Name: Listing
    Fields:
    - Name: TenantId
      Type: i
    - Name: MarketplaceId
      Type: i
    - Name: ExtId
      Type: ss
    - Name: Desc
      Type: ls
    Unique:
    - TenantId
    - MarketplaceId
    - ExtId
  - Name: Marketplace
    Fields:
    - Name: TenantId
      Type: i
    - Name: ExtId
      Type: ss
    - Name: Desc
      Type: ls
    Unique:
    - TenantId
    - ExtId
  - Name: StatusType
    Fields:
    - Name: TenantId
      Type: i
    - Name: ExtId
      Type: ss
    - Name: Desc
      Type: ls
    Unique:
    - TenantId
    - ExtId
  - Name: Status
    Fields:
    - Name: TenantId
      Type: i
    - Name: StatusTypeId
      Type: i
    - Name: Code
      Type: ss
    Unique:
    - TenantId
    - StatusTypeId
    - Code
  - Name: StockItem
    Fields:
    - Name: TenantId
      Type: i
    - Name: ExtId
      Type: ss
    - Name: Desc
      Type: ls
    - Name: InventoryId
      Type: ss
    Unique:
    - TenantId
    - ExtId
  - Name: StockItemAltId
    Fields:
    - Name: TenantId
      Type: i
    - Name: StockItemId
      Type: i
    - Name: AltId
      Type: i
    Unique:
    - n
  - Name: Vendor
    Fields:
    - Name: TenantId
      Type: i
    - Name: ExtId
      Type: ss
    - Name: Desc
      Type: ls
    Unique:
    - n
  - Name: VendorPart
    Fields:
    - Name: TenantId
      Type: i
    - Name: VendorId
      Type: i
    - Name: Nbr
      Type: ss
    - Name: Desc
      Type: ls
    Unique:
    - TenantId
    - VendorId
    - Nbr
  - Name: VendorPartAltId
    Fields:
    - Name: TenantId
      Type: i
    - Name: VendorPartId
      Type: i
    - Name: AltId
      Type: i
    Unique:
    - TenantId
    - VendorPartid
    - AltId
  - Name: VendorPartListingMatch
    Fields:
    - Name: TenantId
      Type: i
    - Name: VendorPartId
      Type: i
    - Name: MarketplaceId
      Type: i
    - Name: ListingId
      Type: i
    - Name: StatusId
      Type: i
    Unique:
    - TenantId
    - VendorPartId
    - MarketplaceId
    - ListingId
  - Name: VendorPartListingAssignment
    Fields:
    - Name: TenantId
      Type: i
    - Name: VendorPartId
      Type: i
    - Name: MarketplaceId
      Type: i
    - Name: ListingId
      Type: i
    Unique:
    - TenantId
    - VendorPartId
    - MarketplaceId
  - Name: VendorPartStockItemMatch
    Fields:
    - Name: TenantId
      Type: i
    - Name: VendorPartId
      Type: i
    - Name: StockItemId
      Type: i
    - Name: StatusId
      Type: i
    Unique:
    - TenantId
    - VendorPartId
    - StockItemId
  - Name: VendorPartStockItemAssignment
    Fields:
    - Name: TenantId
      Type: i
    - Name: VendorPartId
      Type: i
    - Name: StockItemId
      Type: i
    Unique:
    - TenantId
    - VendorPartId
  - Name: Catalog
    Fields:
    - Name: TenantId
      Type: i
    - Name: VendorId
      Type: i
    - Name: ExtId
      Type: ss
    - Name: Desc
      Type: ls
    - Name: LoadedByUserId
      Type: i
    - Name: LoadedDateTime
      Type: dt
    Unique:
    - TenantId
    - VendorId
    - ExtId
  - Name: CatalogItem
    Fields:
    - Name: TenantId
      Type: i
    - Name: CatalogId
      Type: i
    - Name: PartNbr
      Type: ss
    - Name: UnitCost
      Type: d
    - Name: PurchaseOrderUnitOfMeasure
      Type: ss
    - Name: CountPerPurchaseUnit
      Type: i
    - Name: MinPurchaseQty
      Type: i
    - Name: Msrp
      Type: _d
    - Name: Desc
      Type: _ls
    - Name: Upc
      Type: _upc
    Unique:
    - TenantId
    - CatalogId
    - PartNbr
