TableConfig:
  OutputSchema: dbo
  AuditTableNameAppend: History
  TableFieldIndentation: 4
  StartingIdNumber: 65536
  TypeMap:
  - Type: ss
    Output: NVARCHAR(50)
  - Type: ls
    Output: NVARCHAR(500)
  - Type: d
    Output: DECIMAL(19, 6)
  - Type: i
    Output: INT
  - Type: pk
    Output: INT IDENTITY(65536, 1) PRIMARY KEY
  - Type: dt
    Output: DATETIME2
  - Type: bi
    Output: BIGINT
  - Type: guid
    Output: UNIQUEIDENTIFIER
  - Type: upc
    Output: CHAR(12)
  - Type: ean
    Output: CHAR(13)
  - Type: gtin
    Output: CHAR(14)
  - Type: asin
    Output: CHAR(10)
  - Type: b
    Output: BIT
  HistoryTableTypeMap:
  - Type: ss
    Output: NVARCHAR(50)
  - Type: ls
    Output: NVARCHAR(500)
  - Type: d
    Output: DECIMAL(19, 6)
  - Type: i
    Output: INT
  - Type: pk
    Output: INT
  - Type: dt
    Output: DATETIME2
  - Type: bi
    Output: BIGINT
  - Type: guid
    Output: UNIQUEIDENTIFIER
  - Type: upc
    Output: CHAR(12)
  - Type: ean
    Output: CHAR(13)
  - Type: gtin
    Output: CHAR(14)
  - Type: asin
    Output: CHAR(10)
  - Type: b
    Output: BIT
  AuditFields:
  - Name: Id
    Type: pk
  - Name: EffDateTime
    Type: dt
  - Name: ExpDateTime
    Type: dt
  - Name: Ver
    Type: bi
Tables:
  - Name: User
    Fields:
    - Name: TenantId
      Type: i
    - Name: ExtId
      Type: ss
    - Name: Description
      Type: ls
    Unique:
    - TenantId
    - ExtId
    ForeignKeys:
    - Table: Tenant
      Field: TenantId
  - Name: Tenant
    Fields:
    - Name: TenantGuid
      Type: guid
    - Name: Description
      Type: ls
    Unique:
    - TenantGuid
    ForeignKeys: {}
  - Name: AltIdType
    Fields:
    - Name: TenantId
      Type: i
    - Name: ExtId
      Type: ss
    - Name: Description
      Type: ls
    Unique:
    - TenantId
    - ExtId
    ForeignKeys:
    - Table: Tenant
      Field: TenantId
  - Name: AltId
    Fields:
    - Name: TenantId
      Type: i
    - Name: AltIdTypeId
      Type: i
    - Name: AltIdValue
      Type: ss
    Unique:
    - TenantId
    - AltIdTypeId
    - AltIdValue
    ForeignKeys:
    - Table: Tenant
      Field: TenantId
    - Table: AltIdType
      Field: AltiIdTypeId
  - Name: Listing
    Fields:
    - Name: TenantId
      Type: i
    - Name: MarketplaceId
      Type: i
    - Name: ExtId
      Type: ss
    - Name: Description
      Type: ls
    Unique:
    - TenantId
    - MarketplaceId
    - ExtId
    ForeignKeys:
    - Table: Tenant
      Field: TenantId
    - Table: Marketplace
      Field: MarketplaceId
  - Name: Marketplace
    Fields:
    - Name: TenantId
      Type: i
    - Name: ExtId
      Type: ss
    - Name: Description
      Type: ls
    Unique:
    - TenantId
    - ExtId
    ForeignKeys: {}
  - Name: StatusType
    Fields:
    - Name: TenantId
      Type: i
    - Name: ExtId
      Type: ss
    - Name: Description
      Type: ls
    Unique:
    - TenantId
    - ExtId
    ForeignKeys:
    - Table: Tenant
      Field: TenantId
  - Name: Status
    Fields:
    - Name: TenantId
      Type: i
    - Name: StatusTypeId
      Type: i
    - Name: Code
      Type: ss
    Unique:
    - TenantId
    - StatusTypeId
    - Code
    ForeignKeys:
    - Table: Tenant
      Field: TenantId
  - Name: StockItem
    Fields:
    - Name: TenantId
      Type: i
    - Name: ExtId
      Type: ss
    - Name: Description
      Type: ls
    - Name: InventoryId
      Type: ss
    Unique:
    - TenantId
    - ExtId
    ForeignKeys:
    - Table: Tenant
      Field: TenantId
  - Name: StockItemAltId
    Fields:
    - Name: TenantId
      Type: i
    - Name: StockItemId
      Type: i
    - Name: AltId
      Type: i
    Unique: {}
    ForeignKeys:
    - Table: Tenant
      Field: TenantId
  - Name: Vendor
    Fields:
    - Name: TenantId
      Type: i
    - Name: ExtId
      Type: ss
    - Name: Description
      Type: ls
    Unique:
    - TenantId
    - ExtId
    ForeignKeys:
    - Table: Tenant
      Field: TenantId
  - Name: VendorPart
    Fields:
    - Name: TenantId
      Type: i
    - Name: VendorId
      Type: i
    - Name: Nbr
      Type: ss
    - Name: Description
      Type: ls
    Unique:
    - TenantId
    - VendorId
    - Nbr
    ForeignKeys:
    - Table: Tenant
      Field: TenantId
    - Table: Vendor
      Field: VendorId
  - Name: VendorPartAltId
    Fields:
    - Name: TenantId
      Type: i
    - Name: VendorPartId
      Type: i
    - Name: AltId
      Type: i
    Unique:
    - TenantId
    - VendorPartid
    - AltId
    ForeignKeys:
    - Table: Tenant
      Field: TenantId
    - Table: VendorPart
      Field: VendorPartId
  - Name: VendorPartListingMatch
    Fields:
    - Name: TenantId
      Type: i
    - Name: VendorPartId
      Type: i
    - Name: MarketplaceId
      Type: i
    - Name: ListingId
      Type: i
    - Name: StatusId
      Type: i
    Unique:
    - TenantId
    - VendorPartId
    - MarketplaceId
    - ListingId
    ForeignKeys:
    - Table: Tenant
      Field: TenantId
    - Table: VendorPart
      Field: VendorPartId
    - Table: Marketplace
      Field: MarketplaceId
    - Table: Listing
      Field: ListingId
  - Name: VendorPartListingAssignment
    Fields:
    - Name: TenantId
      Type: i
    - Name: VendorPartId
      Type: i
    - Name: MarketplaceId
      Type: i
    - Name: ListingId
      Type: i
    Unique:
    - TenantId
    - VendorPartId
    - MarketplaceId
    ForeignKeys:
    - Table: Tenant
      Field: TenantId
    - Table: VendorPart
      Field: VendorPartId
    - Table: Marketplace
      Field: MarketplaceId
    - Table: Listing
      Field: ListingId
  - Name: VendorPartStockItemMatch
    Fields:
    - Name: TenantId
      Type: i
    - Name: VendorPartId
      Type: i
    - Name: StockItemId
      Type: i
    - Name: StatusId
      Type: i
    Unique:
    - TenantId
    - VendorPartId
    - StockItemId
    ForeignKeys:
    - Table: Tenant
      Field: TenantId
    - Table: VendorPart
      Field: VendorPartId
    - Table: StockItem
      Field: StockItemId
  - Name: VendorPartStockItemAssignment
    Fields:
    - Name: TenantId
      Type: i
    - Name: VendorPartId
      Type: i
    - Name: StockItemId
      Type: i
    Unique:
    - TenantId
    - VendorPartId
    ForeignKeys:
    - Table: Tenant
      Field: TenantId
    - Table: VendorPart
      Field: VendorPartId
    - Table: StockItem
      Field: StockItemId
  - Name: Catalog
    Fields:
    - Name: TenantId
      Type: i
    - Name: VendorId
      Type: i
    - Name: ExtId
      Type: ss
    - Name: Description
      Type: ls
    - Name: LoadedByUserId
      Type: i
    - Name: LoadedDateTime
      Type: dt
    Unique:
    - TenantId
    - VendorId
    - ExtId
    ForeignKeys:
    - Table: Tenant
      Field: TenantId
    - Table: Vendor
      Field: VendorId
  - Name: CatalogItem
    Fields:
    - Name: TenantId
      Type: i
    - Name: CatalogId
      Type: i
    - Name: PartNumber
      Type: ss
    - Name: UnitCost
      Type: d
    - Name: PurchaseOrderUnitOfMeasure
      Type: ss
    - Name: CountPerPurchaseUnit
      Type: i
    - Name: MinPurchaseQty
      Type: i
    - Name: Msrp
      Type: _d
    - Name: Description
      Type: _ls
    - Name: Upc
      Type: _upc
    - Name: Ean
      Type: ean
    - Name: Gtin
      Type: gtin
    - Name: Asin
      Type: asin
    Unique:
    - TenantId
    - CatalogId
    - PartNumber
    ForeignKeys:
    - Table: Tenant
      Field: TenantId
    - Table: Catalog
      Field: CatalogId
