Config:
  AuditSchemaName: audit
  TableFieldIndentation: 4
  TypeMap:
  - Type: ss
    Output: NVARCHAR(50) NOT NULL
  - Type: _ss
    Output: NVARCHAR(50) NULL
  - Type: ls
    Output: NVARCHAR(500)NOT NULL
  - Type: _ls
    Output: NVARCHAR(500)NULL
  - Type: d
    Output: DECIMAL(19, 6) NOT NULL
  - Type: _d
    Output: DECIMAL(19, 6) NULL
  - Type: i
    Output: INT NOT NULL
  - Type: _i
    Output: INT NULL
  - Type: pk
    Output: INT IDENTITY(1, 1) PRIMARY KEY
  - Type: dt
    Output: DATETIMEOFFSET NOT NULL
  - Type: _dt
    Output: DATETIMEOFFSET NULL
  - Type: bi
    Output: BIGINT NOT NULL
  - Type: _bi
    Output: BIGINT NULL
  - Type: guid
    Output:   UNIQUEIDENTIFIER NOT NULL
  AuditFields:
  - Name: Id
    Type: pk
  - Name: EffDateTime
    Type: dt
  - Name: ExpDateTime
    Type: dt
  - Name: Ver
    Type: bi
Tables:
  - Name: Tenant
    Fields:
    - Name: TenantGuid
      Type: guid
    - Name: Desc
      Type: ls
    Unique:
    - TenantGuid
  - Name: ActionType
    Fields:
    - Name: TenantId
      Type: i
    - Name: ExtId
      Type: ss
    - Name: Desc
      Type: ls
    Unique:
    - TenantId
    - ExtId
  - Name: Action
    Fields:
    - Name: TenantId
      Type: i
    - Name: ActionTypeId
      Type: i
    - Name: UserId
      Type: i
    - Name: PerformedDateTime
      Type: dt
    Unique:
    - n
  - Name: User
    Fields:
    - Name: TenantId
      Type: i
    - Name: ExtId
      Type: ss
    - Name: Desc
      Type: ls
    Unique:
    - TenantId
    - ExtId
  - Name: AltIdType
    Fields:
    - Name: TenantId
      Type: i
    - Name: ExtId
      Type: ss
    - Name: Desc
      Type: ls
    Unique:
    - ExtId
  - Name: AltId
    Fields:
    - Name: TenantId
      Type: i
    - Name: AltIdType
      Type: i
    - Name: Value
      Type: ss
    Unique:
    - TenantId
    - AltIdTypeId
    - Value
  - Name: Listing
    Fields:
    - Name: TenantId
      Type: i
    - Name: MarketplaceId
      Type: i
    - Name: ExtId
      Type: ss
    - Name: Desc
      Type: ls
    Unique:
    - TenantId
    - MarketplaceId
    - ExtId
